### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by CodingAdventurer** [puppypvp/spacy-documentation#1]
i downlod the sauce code and i no wok it sai i need aufenticaytion cowed but i nt givein won@???!??@?@#GEY

**Comment by zlddev** [comment]
First, that was not fucking English. Secondly, we clearly stated that the codes reset every 30 minutes for security and copyright purposes. Third and finally, go back to Pre School and learn your ABC's properly. Don't know who taught you but they were clearly drunk.

**Comment by CodingAdventurer** [comment]
your incredibly rude

**Comment by zlddev** [comment]
Banned.
